import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'white-bear-hoodie',
    title: 'White Bear Hoodie',
    category: 'Apparel',
    price: 89,
    episode: 'white-bear',
    description: 'Justice Park premium hoodie. Remember who you were.',
    longDescription: 'Heavyweight 400gsm cotton hoodie featuring the iconic White Bear symbol. Distressed print on front and back. Oversize fit. Part of the Punishment Collection.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 45,
    features: ['Premium 400gsm cotton', 'Distressed screen print', 'Oversized fit', 'Ribbed cuffs and hem'],
  },
  {
    id: 'uss-callister-tee',
    title: 'USS Callister Tee',
    category: 'Apparel',
    price: 45,
    episode: 'uss-callister',
    description: 'Infinity awaits. Space Fleet Division premium tee.',
    longDescription: 'Official USS Callister Space Fleet tee in vintage style. Soft-hand print with crew insignia. Regular fit. Join the infinite crew.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 89,
    features: ['180gsm premium cotton', 'Vintage screen print', 'Regular fit', 'Pre-shrunk'],
  },
  {
    id: 'nosedive-pin-set',
    title: 'Nosedive Pin Set',
    category: 'Accessories',
    price: 29,
    episode: 'nosedive',
    rating: 4.8,
    description: 'Rate everything. Star rating enamel pin collection.',
    longDescription: 'Set of 5 premium enamel pins featuring star ratings from 1.0 to 5.0. Gold-plated backing. Collect them all and show your perfect score.',
    stock: 156,
    features: ['5 enamel pins', 'Gold-plated', 'Secure butterfly clutch', 'Premium gift box'],
  },
  {
    id: 'arkangel-system',
    title: 'ARKANGEL System',
    category: 'Tech',
    price: 0,
    episode: 'arkangel',
    description: 'BLOCKED - Parental controls active.',
    longDescription: 'ACCESS DENIED. This item requires parental authorization.',
    stock: 0,
    features: ['CLASSIFIED', 'RESTRICTED ACCESS', 'AUTHORIZATION REQUIRED'],
  },
  {
    id: 'san-junipero-poster',
    title: 'San Junipero Poster',
    category: 'Art Print',
    price: 65,
    episode: 'san-junipero',
    colors: ['#ff006e', '#00f5ff', '#9d4edd'],
    description: 'Heaven is a place on Earth. Neon sunset art print.',
    longDescription: '24x36" museum-quality print on archival paper. Features the iconic neon sunset and Quagmire club aesthetic. Limited edition of 1987.',
    stock: 34,
    features: ['24x36 inches', 'Archival paper', 'Limited edition', 'Numbered & signed'],
  },
  {
    id: 'grain-memory-unit',
    title: 'Grain Memory Unit',
    category: 'Collectible',
    price: 125,
    episode: 'entire-history',
    description: 'Remember everything. Forget nothing. Replica grain implant.',
    longDescription: 'Museum-quality replica of the Grain memory implant. Display case included. This is a non-functional collectible item.',
    stock: 23,
    features: ['Display case included', 'Numbered certificate', 'Non-functional replica', '1:1 scale'],
  },
  {
    id: '15m-merits-tee',
    title: '15 Million Merits Tee',
    category: 'Apparel',
    price: 42,
    episode: 'fifteen-million',
    description: 'Keep pedaling. Earn your freedom. Premium cycle tee.',
    longDescription: 'Break free from the cycle. Features the iconic bike symbol and merit counter. Soft organic cotton.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 67,
    features: ['Organic cotton', 'Water-based ink', 'Slim fit', 'Sustainable production'],
  },
  {
    id: 'bandersnatch-poster',
    title: 'Choose Your Path Poster',
    category: 'Art Print',
    price: 30,
    episode: 'bandersnatch',
    description: 'Multiple endings. One choice. Interactive art print.',
    longDescription: 'Flowchart-style poster mapping all possible endings. 18x24" on premium stock. Choose wisely.',
    stock: 84,
    features: ['18x24 inches', 'Premium cardstock', 'Matte finish', 'Rolled shipping'],
  },
];

export const SECRET_CODES = {
  SANJUNIPERO: {
    message: 'Heaven is a place on earth. 20% off all neon collection!',
    discount: 'HEAVEN20',
  },
  WHITECHRISTMAS: {
    message: "Cookie detected. You've unlocked the Digital Consciousness collection.",
    discount: 'COOKIE25',
  },
  NOSEDIVE: {
    message: 'Your rating: 4.999 ⭐ - Free shipping unlocked!',
    discount: 'RATING5',
  },
  '15MILLION': {
    message: "You've earned your merits. Exclusive merch bundle unlocked.",
    discount: 'MERITS15',
  },
  BANDERSNATCH: {
    message: 'Wrong path. Or is it? Choose again... or did you already?',
    discount: 'CHOICE10',
  },
  ASHLEYTOO: {
    message: "I'm On A Roll! Ashley Too collection unlocked.",
    discount: 'ASHLEY30',
  },
  USSDEADASS: {
    message: "Captain's orders: 30% off USS Callister merch.",
    discount: 'CAPTAIN30',
  },
};
